### ISSUE TITLE
intergarte tested cell_membrane_polarisation_detector()

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/IGOR_phd#20]
optimize spike removal and test function (if inducing error make sure is consistent - i.e. +/- 0.5mV from non-spiking raw trace)

**Comment by jjb-hub** [comment]
@debapratimj this would now be the highest priority: 

to have it running for APP files: 

1. list of input R for PRE, APP and WASH  e.g. 'inputR_PRE'  'inputR_APP' ect
2. list of RMP (V without )  for PRE, APP and WASH e.g. 'rmp_APP'  'rmp_WASH' ect 


i would imagine a function that I will add to the expandDF() that will add these colums as it builds, 

let me know an ETA - otherwise, I can also build

**Comment by debapratimj** [comment]
Started work 

Current To dos: 

1. Use steady state to calculate V_membrane during PRE APP and WASH, 
2. Fix current error



ETA: 2 days 
so deliverable: 4.1.23

**Comment by debapratimj** [comment]
Debugging this error where the voltage- trace doesnt show up properly and leads to a Boolean error. 

Time: ~12.1.23 
![image](https://github.com/jjb-hub/IGOR_phd/assets/55624846/7df7edcd-96d0-463e-a7ca-8282e432dfa0)


IndexError                                Traceback (most recent call last)
[/Users/owner/Desktop/IGOR_phd/debug.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/debug.ipynb) Cell 2 line 1
     [10](vscode-notebook-cell:/Users/owner/Desktop/IGOR_phd/debug.ipynb#W1sZmlsZQ%3D%3D?line=9) cell_types = np.unique(raw_df_application['cell_id'][:4]) 
     [14](vscode-notebook-cell:/Users/owner/Desktop/IGOR_phd/debug.ipynb#W1sZmlsZQ%3D%3D?line=13) folder_file, cell_id, data_type, drug, conc_uM, replication_no, application_order, drug_in, drug_out, I_set, R_series, R_tip, cell_type, cell_subtype, sex, offset, weight, P_age, Bistable, pAD   = RawDFRow_unpacker(raw_df_application , 0)
---> [16](vscode-notebook-cell:/Users/owner/Desktop/IGOR_phd/debug.ipynb#W1sZmlsZQ%3D%3D?line=15) cell_membrane_polarisation_detector(cell_ID= cell_id, folder_file= folder_file, I_set= I_set , drug=drug , drug_in= drug_in , drug_out= drug_out, application_order=application_order)

File [~/Desktop/IGOR_phd/module/action_potential_functions.py:1453](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/~/Desktop/IGOR_phd/module/action_potential_functions.py:1453), in cell_membrane_polarisation_detector(cell_ID, folder_file, I_set, drug, drug_in, drug_out, I_setting, application_order, pAD_locs)
   [1449](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/~/Desktop/IGOR_phd/module/action_potential_functions.py:1449) v_array_drug = np.array(v_array_drug)
   [1450](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/~/Desktop/IGOR_phd/module/action_potential_functions.py:1450) v_drug_diff  = np.diff(v_array_drug)
-> [1453](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/~/Desktop/IGOR_phd/module/action_potential_functions.py:1453) v_drug_filtered = v_array_drug[np.concatenate(  (   v_drug_diff - np.mean(v_drug_diff)   <= 2*np.std(v_drug_diff)    , [True] ) )]
   [1456](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/~/Desktop/IGOR_phd/module/action_potential_functions.py:1456) v_drug_cleaned, v_drug_peaks  =  array_peak_cleaner(v_array_drug)
   [1458](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/IGOR_phd/~/Desktop/IGOR_phd/module/action_potential_functions.py:1458) fig, axs = plt.subplots(1,1)

IndexError: boolean index did not match indexed array along dimension 0; dimension is 0 but corresponding boolean dimension is 1

**Comment by debapratimj** [comment]
IndexError solved, other main issue was in array_cleaner() also solved, need now one session to put things together, ETA 1 day max

**Comment by debapratimj** [comment]
recent push on issue-20-duplicate has all the necessary function that has been tested on  the subset feature_df. Functions added are : 

1. mean_inputR_APP_calculator(V_df, I_df, drug_in, drug_out) : 
    Returns : input_R_PRE, input_R_APP, input_R_WASH  which are individually lists (dtype is list) of input resistance for each APP condition 

2.  mean_RMP_APP_calculator(V_df, I_df, drug_in, drug_out) : 
     returns : mean_RMP_PRE, mean_RMP_APP, mean_RMP_WASH  which are again lists for mean rest. pot. for each APP condition in the absence of injected current 

3. APP_splitter(v_df, drug_in, drug_out) 
   returns list_PRE, list_APP, list_WASH  which are each lists of voltage values in each condition

**Comment by jjb-hub** [comment]
hello 
1.  which subset feature df - it would be for a single cell_type ?
2. you did not add a spike remover function? or it was already there ? (better to include all added functions so i can also use the generic/modular ones)
3. Please tell me when i should go onto the branch 'issue-20-duplicate' and check it ?
4. delete any unnecessary branches

**Comment by debapratimj** [comment]
1. subset is the entire AP file type
2. I did add: spike_remover(array) returns array_cleaaned 
3. as functions tested on APP dataset, you can check now
4. will delete other branches by 19.1.24

**Comment by jjb-hub** [comment]
Generally the docs need to be more specific.

APP_splitter:
1.  is not called in mean_inputR_APP_calculator or mean_RMP_APP_calculator - which was why i suggested it be written
2. need to include in docs (''' ''') whether it takes the drug_in and drug_out sweep as part of the PRE or APP or WASH and be consistent with use elsewhere

mean_inputR_APP_calculator: 
1. this should return a list for each condition the len of sweeps in condition of the mean RMP of each sweep I do not understand teh docs here 'Calculates RMP or the Resting Membrane Potential based on the V_mean_{condition} and I_injected is zero in this case' 

mean_inputR_APP_calculator:
1. I do not understand what V_mean_{condition} is ? the mean of a sweep ? of all sweeps? I assume a conditon is PRE APP or WASH?
2. 'Returns : input_R_PRE, input_R_APP, input_R_WASH : each a list of input resistances for the condition.' is this one per sweep in which case it is not a mean is that correct?

could you please explain the use case for this: replace_nan_with_mean()

**Comment by debapratimj** [comment]
APP_splitter ():

1. It will be called in the next push.
2. Docs also will be updated. 

mean_inputR_APP_Calculator : 

The docs imply simply that we calculate the RMP per sweep per condtion. So for PRE for instance we put in a np.array of shape say L x S and we get out means of RMP per sweep --> S datapoints in a list. Let me know if this is clear, can update doc description but wanted to be as detailed as possible. 

mean_RMP_APP_Calculator :

1. Mean of each sweep is always returned. condition is PRE/APP/WASH: that is V_mean_{CONDITION} is either V_mean_PRE / V_mean_APP or V_mean_APP as the convention suggests 

2. It is a mean per sweep. Meaning lets consider the voltage array for PRE. Suppose it is of shape L x S : length is L and num of sweeps S. Then the list that is returned for PRE condition is a list with S floats one per sweep. I do not understand how it is not a mean. 

Use case: replace_nan_with_mean():

Often either when the neuron spikes or there might be anomalies in the data, the value crosses significantly over the mean by more than say 2 stds. Then we replace those values with nan. Now if we delete or drop nans, then then lengths of different sweeps / recordings would be different. Instead the nans are replaced with the mean to preserve the lengths

From whatsapp chat: 

Question: Why use V_df when in code we immediately convert it to a np,array? Why dont we instead use V_array? 

A: Firstly, the  variable name legacy V_array, V_df is misleading. I stuck with it as I was keeping tracking of the types and writing code according but V_array really is a List, V_df is correct however, it really is a df. We do not use V_array is it is a 1d array or list and we don't apriori just from the length of this what should be the appropriate shape of the 2d array which is length of each rec x num of sweeps. It can be fed in and reshaped as the len of each recordings are usually the same, but it uses one reshape and could be a point of wrong shaping in case the length of the recording was actually different. V_df seems to be the obvious choice, and i would propose perhaps to return  a np.array from igor_exporter() than a df. 


ETA for proposed changes: 19-20th Jan

**Comment by jjb-hub** [comment]
![Screenshot 2024-01-18 at 18 00 04](https://github.com/jjb-hub/IGOR_phd/assets/120100465/90eade59-a56f-46e8-b17a-9c8f3882437d)
V_array is not a list and has a shape the same as df - inputs have been changed to V_array (once all functions handle arrays yes we can move the iror exporter to only output V_array) this is the V_array available as input (see getters.py line 194) this unpacks everything and will be cleaned once we know what we need (as stated above)

**Comment by jjb-hub** [comment]
to resolve this I will need to make steady_state_value() more generic can you please confirm its inputs and outputs 
![Screenshot 2024-01-18 at 18 34 10](https://github.com/jjb-hub/IGOR_phd/assets/120100465/7f202c46-2ff9-49d0-ab1e-61639cbdd7a3)
why is the steady state V called asym_current? what does it mean ? I need this function to fix mean_inputR_APP_Calculator

**Comment by jjb-hub** [comment]
please do not work on branch issue-20-duplicate ! @debapratimj 

I have rewritten mean_inputR_APP_Calculator (involved modularising steady_state, spike_remover and APP_splitter)
I will test it tonight and if it runs will push so you can look at what needed to be done/ if doesn't run will continue tomorrow

If it runs I will then finish mean_RMP_APP_Calculator tomorrow.

**Comment by debapratimj** [comment]
> ![Screenshot 2024-01-18 at 18 00 04](https://private-user-images.githubusercontent.com/120100465/297821928-90eade59-a56f-46e8-b17a-9c8f3882437d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NzUzNDQsIm5iZiI6MTcwNTY3NTA0NCwicGF0aCI6Ii8xMjAxMDA0NjUvMjk3ODIxOTI4LTkwZWFkZTU5LWE1NmYtNDZlOC1iMTdhLTljOGYzODgyNDM3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxNDM3MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjU2YTlkZTVlMDgxNGJjYzdkNzhjMDAyNTY3NjZhZmMyOWQ0MmU4YTYxOWUxMDg3M2FjNjk1Zjg3NjFkYWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zB5v8fe6iMELTP8nnL7NLQkVxCu-lCbbx0kmwBdNOkI) V_array is not a list and has a shape the same as df - inputs have been changed to V_array (once all functions handle arrays yes we can move the iror exporter to only output V_array) this is the V_array available as input (see getters.py line 194) this unpacks everything and will be cleaned once we know what we need (as stated above)

Look here: 
<img width="1040" alt="image" src="https://github.com/jjb-hub/IGOR_phd/assets/55624846/3d08e5e6-05d5-4459-924d-5b39d0f6bd2b">

What I was referring to is what is returned from igor_exporter(): It returns a V_array and a V_df. In the image you sent, you actually use what I said, ie. taking V_df and converting it to np. array. So we actually are talking about the same thing

**Comment by jjb-hub** [comment]
![Screenshot 2024-01-19 at 16 02 26](https://github.com/jjb-hub/IGOR_phd/assets/120100465/cdb9f857-1ca8-4a33-9002-e45b5392bce0)
the screenshot you posted is not the code that is being used (i do not know from where it comes) - getters.py is where functions are applied (see screenshot) - until other things are built it will stay like this

**Comment by debapratimj** [comment]
Adding new function for spike_remover that cleans spikes in case of regular spiking : 

CODE: 


def spike_remover_mod(array):

    '''
    Cleans a voltage array by removing spikes
    Input: array: voltage  np.array : shape : length x num_sweeps 
    (Note that when using igor exporter, this is actually df_V and NOT V_array although V_array when reshaped quickly gives the same result)
    Returns: array_cleaned: voltage np.array  with peaks removed, shape : length x num_sweeps  
    '''
    
    array_cleaned  = array.copy() 

    if array.shape[0] <= 1 :
        print('Voltage array has 1 or fewer points')
        return array_cleaned
    else:
        pass
    

    array_diff_abs = np.abs(np.diff(array, axis = 0))
    array_diff_abs = np.vstack([array_diff_abs, np.mean(array_diff_abs, axis  = 0 ).reshape(1,-1) ])
    
    array_cleaned[array > np.mean(array , axis = 0 ) + 2*np.std(array, axis =  0 )] = np.nan

    array_cleaned = replace_nan_with_mean(array_cleaned)

    return array_cleaned  

Code Usage: 

folder_name =  'JJB210427/t8'  #'JJB210406/t11' 





path_V, path_I = make_path(folder_name)
V_array, V_df = igor_exporter(path_V)   
V_array = np.array(V_df)


V_array_cleaned = spike_remover_mod(V_array) 
V_array_cleaned = spike_remover_mod(V_array_cleaned) # can use twice for slightly better performance


    


USE CASES :  tested on : folder_file:   'JJB210406/t11' 
Example Traces:

![image](https://github.com/jjb-hub/IGOR_phd/assets/55624846/f1e8a5bf-8e50-495b-93f4-79130e81edfd)

USE CASES :  tested on : folder_file:  'JJB210427/t8'
Example Traces: 
1. Fewer Spikes: 
![image](https://github.com/jjb-hub/IGOR_phd/assets/55624846/283a885b-1b3b-482e-b6ba-60720562cb57)
2. Regular/Tonic Spiking: 
![image](https://github.com/jjb-hub/IGOR_phd/assets/55624846/3bd373f2-9c7e-406c-ab65-0af4877d8dce)

**Comment by debapratimj** [comment]
As we don't need to use np.diff() in spike_remover, those lines can be deleted: 


def spike_remover_mod(array):

    '''
    Cleans a voltage array by removing spikes
    Input: array: voltage  np.array : shape : length x num_sweeps 
    (Note that when using igor exporter, this is actually df_V and NOT V_array although V_array when reshaped quickly gives the same result)
    Returns: array_cleaned: voltage np.array  with peaks removed, shape : length x num_sweeps  
    '''
    
    array_cleaned  = array.copy() 

    if array.shape[0] <= 1 :
        print('Voltage array has 1 or fewer points')
        return array_cleaned
    else:
        pass
    
    array_cleaned[array > np.mean(array , axis = 0 ) + 2*np.std(array, axis =  0 )] = np.nan

    array_cleaned = replace_nan_with_mean(array_cleaned)

    return array_cleaned

**Comment by debapratimj** [comment]
issue-20-cell-membrane-polarisation-detector  was checked and is a redundant branch and can be deleted

**Comment by jjb-hub** [comment]
rewritten
