### ISSUE TITLE
On entry to DLASCLS parameter number  4 had an illegal value

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/IGOR_phd#26]
FP (firing property issues)
JJB230830/t44 see bellow in function extract_FI_slope_and_rheobased_threshold()
![Screen Shot 2023-11-27 at 16 03 25](https://github.com/jjb-hub/IGOR_phd/assets/120100465/b615950c-e349-42fd-9bbd-795a8b4a453b)

AP (application functions)
#18 shows this issue with trace JJB230830/t41 ... but seems to run now 
error message same =  ** On entry to DLASCLS parameter number  4 had an illegal value

**Comment by jjb-hub** [comment]
# #BREAKS ON 
# FP type file
# JJB230830/t44
# AND
# AP type file
# JJB230830/t41
# /Users/jasminebutler/Desktop/IGOR_phd/.venv/lib/python3.8/site-packages/numpy/lib/polynomial.py:628: RuntimeWarning: invalid value encountered in true_divide
#   lhs /= scale
#  ** On entry to DLASCLS parameter number  4 had an illegal value
#  ** On entry to DLASCLS parameter number  4 had an illegal value
#  ** On entry to DLASCLS parameter number  4 had an illegal value
#  ** On entry to DLASCLS parameter number  4 had an illegal value
#  ** On entry to DLASCLS parameter number  5 had an illegal value
#  ** On entry to DLASCLS parameter number  4 had an illegal value

**Comment by jjb-hub** [comment]
here is my pip list incase we have conflicts from there ? (.venv) (base) DeepPsycExplorer-2:IGOR_phd jasminebutler$ pip list 
Package            Version
------------------ ---------
appnope            0.1.3
asttokens          2.2.1
backcall           0.2.0
Brotli             1.0.9
certifi            2023.5.7
cffi               1.15.1
charset-normalizer 3.1.0
comm               0.1.3
contourpy          1.0.7
cssselect2         0.7.0
cycler             0.11.0
Cython             0.29.35
debugpy            1.6.7
decorator          5.1.1
et-xmlfile         1.1.0
executing          1.2.0
fonttools          4.39.4
html5lib           1.1
idna               3.4
igor               0.3
importlib-metadata 6.6.0
ipykernel          6.23.1
ipython            8.12.2
jedi               0.18.2
joblib             1.2.0
jupyter_client     8.2.0
jupyter_core       5.3.0
kiwisolver         1.4.4
lazy_loader        0.2
littleutils        0.2.2
matplotlib         3.6.3
matplotlib-inline  0.1.6
nest-asyncio       1.5.6
numpy              1.19.0
openpyxl           3.1.2
outdated           0.2.2
outlier-utils      0.0.3
packaging          23.1
pandas             1.4.4
pandas-flavor      0.5.0
parso              0.8.3
patsy              0.5.3
pexpect            4.8.0
pickleshare        0.7.5
Pillow             9.5.0
pingouin           0.5.3
pip                23.1.2
platformdirs       3.5.1
prompt-toolkit     3.0.38
psutil             5.9.5
ptyprocess         0.7.0
pure-eval          0.2.2
pycparser          2.21
pydyf              0.6.0
Pygments           2.15.1
pyparsing          3.0.9
pyphen             0.14.0
python-dateutil    2.8.2
pytz               2023.3
pyzmq              25.1.0
requests           2.31.0
scikit-learn       1.2.2
scipy              1.9.3
seaborn            0.11.2
setuptools         67.8.0
six                1.16.0
sklearn            0.0.post5
stack-data         0.6.2
statannot          0.2.3
statannotations    0.5.0
statsmodels        0.14.0
tabulate           0.9.0
threadpoolctl      3.1.0
tinycss2           1.2.1
tornado            6.3.2
traitlets          5.9.0
typing_extensions  4.6.3
urllib3            2.0.2
wcwidth            0.2.6
weasyprint         59.0
webencodings       0.5.1
wheel              0.40.0
xarray             2022.9.0
zipp               3.15.0
zopfli             0.2.2

**Comment by jjb-hub** [comment]
@debapratimj this was your old notes - I am cleaning up the requirements txt 

## pythong 3.8.5 - DJ working on spyder
# (base) C:\Users\debap\IGOR_phd>pip list
# Package                       Version
# ----------------------------- -------------------
# alabaster                     0.7.13
# anaconda-client               1.7.2
# anaconda-navigator            1.10.0
# argon2-cffi                   20.1.0
# arrow                         1.2.3
# astroid                       2.15.4
# asttokens                     2.2.1
# async-generator               1.10
# atomicwrites                  1.4.1
# attrs                         21.2.0
# autopep8                      2.0.2
# Babel                         2.12.1
# backcall                      0.2.0
# backports.functools-lru-cache 1.6.4
# backports.tempfile            1.0
# backports.weakref             1.0.post1
# bcrypt                        4.0.1
# beautifulsoup4                4.9.3
# binaryornot                   0.4.4
# black                         23.3.0
# bleach                        3.2.1
# Brian2                        2.5.0.1
# brotlipy                      0.7.0
# certifi                       2020.6.20
# cffi                          1.14.5
# chardet                       4.0.0
# click                         8.0.1
# cloudpickle                   2.2.1
# clyent                        1.2.2
# colorama                      0.4.6
# colorspacious                 1.1.2
# comm                          0.1.3
# conda                         4.10.1
# conda-build                   3.20.5
# conda-package-handling        1.7.3
# conda-verify                  3.4.2
# contourpy                     1.0.7
# cookiecutter                  2.1.1
# cryptography                  3.4.7
# cycler                        0.10.0
# Cython                        0.29.25
# debugpy                       1.6.7
# decorator                     4.4.2
# defusedxml                    0.6.0
# diff-match-patch              20230430
# dill                          0.3.6
# docstring-to-markdown         0.12
# docutils                      0.19
# entrypoints                   0.3
# et-xmlfile                    1.1.0
# exceptiongroup                1.1.1
# executing                     1.2.0
# filelock                      3.0.12
# flake8                        6.0.0
# fonttools                     4.39.4
# future                        0.18.2
# glob2                         0.7
# idna                          2.10
# igor                          0.3
# imagesize                     1.4.1
# importlib-metadata            6.6.0
# importlib-resources           5.12.0
# inflection                    0.5.1
# iniconfig                     2.0.0
# intervaltree                  3.1.0
# ipykernel                     6.23.0
# ipython                       8.12.2
# ipython-genutils              0.2.0
# ipywidgets                    7.5.1
# isort                         5.12.0
# jaraco.classes                3.2.3
# jedi                          0.18.0
# jellyfish                     0.11.2
# Jinja2                        3.0.0
# jinja2-time                   0.2.0
# joblib                        1.2.0
# jsonschema                    3.2.0
# jupyter                       1.0.0
# jupyter-client                8.2.0
# jupyter-console               6.2.0
# jupyter-core                  5.3.0
# jupyterlab-pygments           0.1.2
# keyring                       23.13.1
# kiwisolver                    1.3.1
# lazy-object-proxy             1.9.0
# libarchive-c                  2.9
# MarkupSafe                    2.0.1
# matplotlib                    3.7.1
# matplotlib-inline             0.1.6
# matplotlib-scalebar           0.8.1
# mccabe                        0.7.0
# menuinst                      1.4.16
# mistune                       0.8.4
# mkl-fft                       1.3.0
# mkl-random                    1.2.1
# mkl-service                   2.3.0
# more-itertools                9.1.0
# mpmath                        1.2.1
# mypy-extensions               1.0.0
# navigator-updater             0.2.1
# nbclient                      0.5.1
# nbconvert                     6.0.7
# nbformat                      5.1.3
# nest-asyncio                  1.4.1
# notebook                      6.1.4
# numpy                         1.20.2
# numpydoc                      1.5.0
# olefile                       0.46
# openpyxl                      3.1.2
# packaging                     23.1
# pandas                        1.1.3
# pandocfilters                 1.4.2
# paramiko                      3.1.0
# parso                         0.8.0
# pathspec                      0.11.1
# pexpect                       4.8.0
# pickleshare                   0.7.5
# Pillow                        8.2.0
# pip                           21.1.1
# pkginfo                       1.7.0
# platformdirs                  3.5.0
# plottools                     0.2.0
# pluggy                        1.0.0
# prometheus-client             0.8.0
# prompt-toolkit                3.0.38
# psutil                        5.8.0
# ptyprocess                    0.7.0
# pure-eval                     0.2.2
# py-cpuinfo                    8.0.0
# pycodestyle                   2.10.0
# pycosat                       0.6.3
# pycparser                     2.20
# pydocstyle                    6.3.0
# pyflakes                      3.0.1
# Pygments                      2.15.1
# pylint                        2.17.4
# pylint-venv                   3.0.1
# pyls-spyder                   0.4.0
# PyNaCl                        1.5.0
# pyOpenSSL                     20.0.1
# pyparsing                     2.4.7
# PyQt5                         5.15.9
# PyQt5-Qt5                     5.15.2
# PyQt5-sip                     12.12.1
# PyQtWebEngine                 5.15.6
# PyQtWebEngine-Qt5             5.15.2
# pyrsistent                    0.17.3
# PySocks                       1.7.1
# pytest                        7.3.1
# python-dateutil               2.8.2
# python-lsp-black              1.2.1
# python-lsp-jsonrpc            1.0.0
# python-lsp-server             1.7.2
# python-slugify                8.0.1
# pytoolconfig                  1.2.5
# pytz                          2021.1
# pywin32                       306
# pywin32-ctypes                0.2.0
# pywinpty                      0.5.7
# PyYAML                        5.4.1
# pyzmq                         25.0.2
# QDarkStyle                    3.1
# qstylizer                     0.2.2
# QtAwesome                     1.2.3
# qtconsole                     5.4.3
# QtPy                          2.3.1
# requests                      2.25.1
# rope                          1.8.0
# Rtree                         1.0.1
# ruamel-yaml-conda             0.15.100
# scikit-learn                  1.2.2
# scipy                         1.10.1
# seaborn                       0.11.0
# Send2Trash                    1.5.0
# setuptools                    52.0.0.post20210125
# sip                           4.19.13
# six                           1.15.0
# sklearn                       0.0.post5
# snowballstemmer               2.2.0
# sortedcontainers              2.4.0
# sounddevice                   0.4.1
# soupsieve                     2.2.1
# sphinx                        7.0.0
# sphinxcontrib-applehelp       1.0.4
# sphinxcontrib-devhelp         1.0.2
# sphinxcontrib-htmlhelp        2.0.1
# sphinxcontrib-jsmath          1.0.1
# sphinxcontrib-qthelp          1.0.3
# sphinxcontrib-serializinghtml 1.1.5
# spyder                        5.4.3
# spyder-kernels                2.4.3
# stack-data                    0.6.2
# sympy                         1.9
# terminado                     0.9.1
# testpath                      0.4.4
# text-unidecode                1.3
# textdistance                  4.5.0
# threadpoolctl                 3.1.0
# three-merge                   0.1.1
# tinycss2                      1.2.1
# toml                          0.10.2
# tomli                         2.0.1
# tomlkit                       0.11.8
# tornado                       6.3.1
# tqdm                          4.59.0
# traitlets                     5.9.0
# typing-extensions             4.5.0
# ujson                         5.7.0
# urllib3                       1.26.4
# watchdog                      3.0.0
# wcwidth                       0.2.5
# webencodings                  0.5.1
# whatthepatch                  1.0.5
# wheel                         0.36.2
# widgetsnbextension            3.5.1
# win-inet-pton                 1.1.0
# wincertstore                  0.2
# wrapt                         1.15.0
# xlrd                          2.0.1
# xmltodict                     0.12.0
# yapf                          0.32.0
# zipp                          3.4.1

**Comment by debapratimj** [comment]
Found typo in code:  Change cell_ID to cell_id as key under metabuild_functions.py

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/Users/owner/Desktop/random/RUN.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/RUN.ipynb) Cell 3 line 1
      [8](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=7) L5a_TLX_df = df.loc[(df['cell_type']=='L5a_TLX')& (df['data_type']=='AP')]
      [9](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=8) L5a_TLX_df
---> [11](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=10) expandFeatureDF(L5a_TLX_df) 
     [12](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=11) #
     [13](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=12) # #BREAKS ON 
     [14](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=13) # FP type file
   (...)
     [25](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=24) #  ** On entry to DLASCLS parameter number  5 had an illegal value
     [26](vscode-notebook-cell:/Users/owner/Desktop/random/RUN.ipynb#W2sZmlsZQ%3D%3D?line=25) #  ** On entry to DLASCLS parameter number  4 had an illegal value

File [~/Desktop/random/module/metabuild_functions.py:156](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/module/metabuild_functions.py:156), in expandFeatureDF(filename_or_df)
    [153](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/module/metabuild_functions.py:153)     df=filename_or_df
    [155](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/module/metabuild_functions.py:155) og_columns = df.columns.copy() #origional columns #for ordering columns
--> [156](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/module/metabuild_functions.py:156) df['mouseline'] = df.cell_ID.str[:3]
    [157](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/module/metabuild_functions.py:157) df = df.apply(_handleFile, axis=1) #Apply a function along an axis (rows = 1) of the DataFrame
    [159](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/module/metabuild_functions.py:159) #ORDERING DF internal: like this new columns added will appear at the end of the df in the order they were created in _handelfile()

File [~/Desktop/random/.venv/lib/python3.8/site-packages/pandas/core/generic.py:5139](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/.venv/lib/python3.8/site-packages/pandas/core/generic.py:5139), in NDFrame.__getattr__(self, name)
   [5137](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/.venv/lib/python3.8/site-packages/pandas/core/generic.py:5137) if self._info_axis._can_hold_identifiers_and_holds_name(name):
   [5138](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/.venv/lib/python3.8/site-packages/pandas/core/generic.py:5138)     return self[name]
-> [5139](https://file+.vscode-resource.vscode-cdn.net/Users/owner/Desktop/random/~/Desktop/random/.venv/lib/python3.8/site-packages/pandas/core/generic.py:5139) return object.__getattribute__(self, name)

AttributeError: 'DataFrame' object has no attribute 'cell_ID'

**Comment by debapratimj** [comment]
Issue exists in igor_exporter() function, 

Traceback returns np.array of zeros though data exists, 

ETA: Friday eve/Sat morning latest

**Comment by jjb-hub** [comment]
jumped on the branch today and I am still getting the same error:

** On entry to DLASCLS parameter number  4 had an illegal value

I ran this cell in the RUN notebook:
![Screen Shot 2023-12-24 at 14 25 17](https://github.com/jjb-hub/IGOR_phd/assets/120100465/b8342c29-bbd5-4b5e-b0d6-b5eb80079f21)

and have several files that have this error:
![Screen Shot 2023-12-24 at 14 37 06](https://github.com/jjb-hub/IGOR_phd/assets/120100465/f9bcca30-5e52-4805-ab1b-25a5f020069b)
![Screen Shot 2023-12-24 at 14 37 27](https://github.com/jjb-hub/IGOR_phd/assets/120100465/8564781b-eaa0-48df-8d7c-2338fb16b6dd)
![Screen Shot 2023-12-24 at 14 37 42](https://github.com/jjb-hub/IGOR_phd/assets/120100465/6dc6cb1d-716c-4367-ab01-96fc1efa139a)


PN: i see that when i look at the finished df the column 'error' does not have this message in it but it is printed out in the run of getorbuildExpandedDF(), I will look into this now on my branch as there is evidently something wrong with my handling if the error and traceback columns. This includes the following errors: 

![Screen Shot 2023-12-24 at 14 38 30](https://github.com/jjb-hub/IGOR_phd/assets/120100465/616ee91f-f7a7-4d35-b8e6-1813f91c68d4)
![Screen Shot 2023-12-24 at 14 38 51](https://github.com/jjb-hub/IGOR_phd/assets/120100465/377a6daa-525e-478d-97b5-be79794d4b4d)
![Screen Shot 2023-12-24 at 14 39 06](https://github.com/jjb-hub/IGOR_phd/assets/120100465/4bdc1167-0731-424f-81f8-a739116df326)
![Screen Shot 2023-12-24 at 14 39 24](https://github.com/jjb-hub/IGOR_phd/assets/120100465/40a7b6a1-b973-4020-9e96-f4ab2d9d38a8)
![Screen Shot 2023-12-24 at 14 39 36](https://github.com/jjb-hub/IGOR_phd/assets/120100465/9d64d3a2-e508-4a54-b53d-191832fbb9c8)

**Comment by debapratimj** [comment]
error message same = ** On entry to DLASCLS parameter number 4 had an illegal value "
Issue caused due to extract_FI_x_y function that had an incorrect logic on how the x values (current injection values) would be calculated and it would give us a bunch of zeros. Then np.polyfit would fail to do a linear fit on x,y as all the x values were the same. extract_FI_x_y was corrected so the error no longer appears. Solved on dj_issues26&28 and merged with jasmine branch.
