### ISSUE TITLE
FIX TypeError ap_characteristics_extractor_subroutine_derivative

### ISSUE THREAD

**Issue by jjb-hub** [jjb-hub/IGOR_phd#28]
expandDF now adds columns 'error' and 'traceback' to the expandedDF (i needed this so I can work on the files that do run and you can easily identify where bugs are coming from)

the vast majority of files have this error - could you please help me understand why and resolve it 

ap_characteristics_extractor_subroutine_derivative(V_dataframe, sweep_num) as called in _handelfile()
TypeError: cannot unpack non-iterable NoneType object

ADDITIONALLY: if there are no APs in a trace I would like the columns 'AP_locs' and pAD_count'  to have 0 not NaN

**Comment by jjb-hub** [comment]
FI_slope works but AP_height no!

**Comment by jjb-hub** [comment]
![Screen Shot 2023-12-05 at 19 01 54](https://github.com/jjb-hub/IGOR_phd/assets/120100465/8eec94a8-a697-4385-91ef-5bfe4f1c2d03)
here is a cell in the notebook that can be used to have a look at whats is happening

**Comment by debapratimj** [comment]
TypeError: cannot unpack non-iterable NoneType object 

Issue solved by returning correct variables calculated by subroutine_derivative. Otherwise it was trying to unpack a NoneTyoe object and hence the error. Solved on djissues26&28 and merged with jasmine branch
