### ISSUE TITLE
requirements for environment on dj's system

### ISSUE THREAD

**Issue by debapratimj** [jjb-hub/IGOR_phd#29]
Basic specs: 

ProductName:	macOS
ProductVersion:	12.6.6
BuildVersion:	21G646

Python 3.8.5 
pip 23.3.2
setuptools 69.0.2

[dj_requirements.txt](https://github.com/jjb-hub/IGOR_phd/files/13721033/dj_requirements.txt)

**Comment by jjb-hub** [comment]
testing igor2

https://pypi.org/project/igor2/#description

**Comment by debapratimj** [comment]
Have migrated now to igor2, issue can be closed
